/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventory;

import java.awt.Toolkit;
import javax.swing.*;
import java.sql.*;
import net.proteanit.sql.*;

/**
 *
 * @author server-pc
 */
public class UserAccounts extends javax.swing.JFrame {
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form UserAccounts
     */
    
    private static UserAccounts obj = null;
    
    private UserAccounts() {
        initComponents();
        conn = javaconnect.ConnecrDb();
        hideHelp();
        updateUATable();
        setIcon();
    }
    
    public static UserAccounts getObj() {
        if (obj == null){
            obj = new UserAccounts();
        }
        return obj;
    }
    
    public void setIcon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon1.png")));
    }
        private void updateUATable(){
        try{
            //Initializes the SQL statement
            String sql = "select Username,Password,Alias,Type from accounts ";
            pst = conn.prepareStatement(sql); //Prepares the sql statement
            rs = pst.executeQuery(); //Executes the prepared sql statement
            //Fill the contents of the Equipments table
            //to tbpEquipUpd
            tblUA.setModel(DbUtils.resultSetToTableModel(rs));
            
        //Adds a SQLException, that will display "Incorrect SQL Syntax
        //in console if the SQL statement executed is incorrect
        }catch(SQLException e){
            System.err.println("Incorrect SQL Syntax");
        }
    }
    
    private void editUA(){
        try{
            String id = txtID.getText();
            String user = txtUser.getText();
            String pass = txtPass.getText();
            String alias = txtAlias.getText();
            String type = txtType.getText();
            
            String sql = "update accounts set username='"+user+"', "
                    + "password='"+pass+"', alias='"+alias+"', type='"+type+"' " 
                    + "where account_id='"+id+"' ";
            pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Information Updated",
                    "Updated",JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception e){
            e.printStackTrace();
        }
        updateUATable();
    }
    
    private void addUA(){
        try{
            String sql = "insert into accounts (username,password,alias,type) "
                    + "values (?,?,?,?)";
            pst = conn.prepareStatement(sql);
            pst.setString(1, txtUser.getText());
            pst.setString(2, txtPass.getText());
            pst.setString(3, txtAlias.getText());
            pst.setString(4, txtType.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Information Saved!",
                    "Saved to Database",JOptionPane.INFORMATION_MESSAGE);
        }catch(SQLException e){
            System.err.println("Invalid SQL Syntax!");
            e.printStackTrace();
        }catch(Exception e){
            e.printStackTrace();
        }
        updateUATable();
    }
    
    private void hideHelp(){
        lblHelper.setVisible(false);
        txtID.setVisible(false);
        lblUser.setVisible(false);
    }
    
    private void clearText(){
        txtUser.setText("");
        txtPass.setText("");
        txtConfirm.setText("");
        txtAlias.setText("");
        txtType.setText("Assistant");
    }
    
    private void disableComponents(){
        txtUser.setEnabled(false);
        txtPass.setEnabled(false);
        txtConfirm.setEnabled(false);
        txtAlias.setEnabled(false);
        txtType.setEnabled(false);
        cmdSave.setEnabled(false);
        cmdCancel.setEnabled(false);
        cmdAdd.setEnabled(true);
        cmdUpd.setEnabled(true);
        cmdDel.setEnabled(true);
        txtUASearchF.setEnabled(true);
    }
    
    private void enableComponents(){
        txtUser.setEnabled(true);
        txtPass.setEnabled(true);
        txtConfirm.setEnabled(true);
        txtAlias.setEnabled(true);
        txtType.setEnabled(true);
        cmdSave.setEnabled(true);
        cmdCancel.setEnabled(true);
        cmdAdd.setEnabled(false);
        cmdUpd.setEnabled(false);
        cmdDel.setEnabled(false);
        txtUASearchF.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtType = new javax.swing.JTextField();
        cmdSave = new javax.swing.JButton();
        cmdCancel = new javax.swing.JButton();
        txtAlias = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        txtConfirm = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        cmdAdd = new javax.swing.JButton();
        cmdUpd = new javax.swing.JButton();
        cmdDel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtUASearchF = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        lblHelper = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUA = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtUASearchT = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("User Accounts");
        setName("frmUA"); // NOI18N
        setResizable(false);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Username");

        jLabel4.setText("Password");

        jLabel5.setText("Alias");

        jLabel6.setText("Account Type");

        txtUser.setDocument(new JTextFieldLimit(20));
        txtUser.setEnabled(false);
        txtUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUserKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUserKeyReleased(evt);
            }
        });

        txtType.setEditable(false);
        txtType.setText("Assistant");
        txtType.setEnabled(false);

        cmdSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/gfxresources/Save.png"))); // NOI18N
        cmdSave.setMnemonic('s');
        cmdSave.setText("Save");
        cmdSave.setEnabled(false);
        cmdSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSaveActionPerformed(evt);
            }
        });

        cmdCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/gfxresources/Cancel.png"))); // NOI18N
        cmdCancel.setMnemonic('c');
        cmdCancel.setText("Cancel");
        cmdCancel.setEnabled(false);
        cmdCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCancelActionPerformed(evt);
            }
        });

        txtAlias.setDocument(new JTextFieldLimit(15));
        txtAlias.setEnabled(false);
        txtAlias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAliasKeyPressed(evt);
            }
        });

        txtPass.setDocument(new JTextFieldLimit(20));
        txtPass.setEnabled(false);
        txtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPassKeyPressed(evt);
            }
        });

        txtConfirm.setDocument(new JTextFieldLimit(20));
        txtConfirm.setEnabled(false);
        txtConfirm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtConfirmKeyPressed(evt);
            }
        });

        jLabel7.setText("Confirm Password");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(cmdSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(cmdCancel))
                    .addComponent(txtType, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAlias, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtUser, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPass, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtConfirm, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAlias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdSave)
                    .addComponent(cmdCancel))
                .addContainerGap())
        );

        cmdAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/gfxresources/monitor_add.png"))); // NOI18N
        cmdAdd.setMnemonic('a');
        cmdAdd.setText("Add");
        cmdAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAddActionPerformed(evt);
            }
        });

        cmdUpd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/gfxresources/monitor_edit.png"))); // NOI18N
        cmdUpd.setMnemonic('e');
        cmdUpd.setText("Update");
        cmdUpd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdUpdActionPerformed(evt);
            }
        });

        cmdDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/gfxresources/monitor_delete.png"))); // NOI18N
        cmdDel.setMnemonic('d');
        cmdDel.setText("Delete");
        cmdDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDelActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/gfxresources/search.png"))); // NOI18N
        jLabel1.setText("Search");

        txtUASearchF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUASearchFKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUASearchFKeyReleased(evt);
            }
        });

        lblHelper.setText("l");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtUASearchF))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmdDel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmdUpd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmdAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblHelper)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblUser)))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(cmdAdd)
                        .addGap(50, 50, 50)
                        .addComponent(cmdUpd)
                        .addGap(52, 52, 52)
                        .addComponent(cmdDel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHelper)
                            .addComponent(lblUser)))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUASearchF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Form View", jPanel1);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblUA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblUA);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/gfxresources/search.png"))); // NOI18N
        jLabel2.setText("Search");

        txtUASearchT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUASearchTKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUASearchTKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtUASearchT)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUASearchT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Table View", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAddActionPerformed
        String type = new Main().lblType.getText();
        if(type.equals("Developer")){
            txtType.setEditable(true);
            lblHelper.setText("AddUA");
            enableComponents();
            clearText();
        }else{
            lblHelper.setText("AddUA");
            enableComponents();
            clearText();
        }
    }//GEN-LAST:event_cmdAddActionPerformed

    private void cmdUpdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdUpdActionPerformed
        String type = new Main().lblType.getText();
        if(type.equals("Developer")){
            String id = txtID.getText();
            if(id.equals("")){
                JOptionPane.showMessageDialog(null, "No Data to be Updated", 
                        "No Data",JOptionPane.WARNING_MESSAGE);
            }else{
                txtType.setEditable(true);
                lblHelper.setText("UpdUA");
                enableComponents();
                txtUser.setEnabled(false);
            }
        }else{
            String id = txtID.getText();
            if(id.equals("")){
                JOptionPane.showMessageDialog(null, "No Data to be Updated", 
                        "No Data",JOptionPane.WARNING_MESSAGE);
            }else{
                lblHelper.setText("UpdUA");
                enableComponents();
                txtUser.setEnabled(false);
            }
        }
    }//GEN-LAST:event_cmdUpdActionPerformed

    private void cmdSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSaveActionPerformed
        String user = txtUser.getText();
        String pass = txtPass.getText();
        String confirm = txtConfirm.getText();
        String alias = txtAlias.getText();
        if(lblUser.getText().equals(txtUser.getText())){
            JOptionPane.showMessageDialog(null,"Username already exist!",
                "Duplicate Username",JOptionPane.ERROR_MESSAGE);
            txtUser.setText("");
        }else if ((user.equals("")) || ((pass.equals("")) || (confirm.equals("")) ||
                (alias.equals("")))){
            JOptionPane.showMessageDialog(null, "Fill-up the blank fields!", "Blank Field",
                    JOptionPane.WARNING_MESSAGE);
        }else{
            String a = "AddUA";
            String u = "UpdUA";
            if (a.equals(lblHelper.getText())){
                if (txtPass.getText().equals(txtConfirm.getText())){
                    addUA();
                    System.out.println("Add");
                    clearText();
                    disableComponents();
                }else{
                    JOptionPane.showMessageDialog(null,"Passwords did not match","Passwords don't match",
                            JOptionPane.ERROR_MESSAGE);
                }
            }else if(u.equals(lblHelper.getText())){
                if (txtPass.getText().equals(txtConfirm.getText())){
                    editUA();
                    System.out.println("Updated");
                    clearText();
                    disableComponents();
                }else{
                    JOptionPane.showMessageDialog(null,"Passwords did not match","Passwords don't match",
                            JOptionPane.ERROR_MESSAGE);                
                }
            }else{
                System.err.println("error!");
            }
        }
    }//GEN-LAST:event_cmdSaveActionPerformed

    private void cmdDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDelActionPerformed
        String id = txtID.getText();
        if(id.equals("")){
            JOptionPane.showMessageDialog(null, "No Information selected",
                    "Cannot delete Empty record",JOptionPane.ERROR_MESSAGE);
        }else{
            if(id.equals("")){
                JOptionPane.showMessageDialog(null,"No Information selected",
                        "Cannot delete Empty record",JOptionPane.ERROR_MESSAGE);
            }else{
                int q = JOptionPane.showConfirmDialog(null,
                        "Do you really want to delete the selected information?","Delete Record",
                        JOptionPane.YES_NO_OPTION);
                if (q==0){
                    String sql = "delete from accounts where account_id =?";
                    try{
                        pst = conn.prepareStatement(sql);
                        pst.setString(1, id);
                        pst.execute();
                        JOptionPane.showMessageDialog(null, "Information Deleted!",
                                "Deleted to Database",JOptionPane.INFORMATION_MESSAGE);
                    }catch(SQLException e){
                        System.err.println("Invalid SQL Syntax!");
                    }catch(Exception e){
                        e.printStackTrace();
                    }
                    updateUATable();
                    clearText();
                    txtID.setText("");
                }
            }
        }
    }//GEN-LAST:event_cmdDelActionPerformed

    private void cmdCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCancelActionPerformed
        disableComponents();
        clearText();
    }//GEN-LAST:event_cmdCancelActionPerformed

    private void txtUserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserKeyReleased
        String user = txtUser.getText();
        if(user.equals("")){
            
        }else{
            try{
                String sql = "select * from accounts where username=?";
                pst = conn.prepareStatement(sql);
                pst.setString(1, txtUser.getText());
                rs = pst.executeQuery();              
                if(rs.next()){
                    String usr = rs.getString("username");
                    lblUser.setText(usr);
                }
            }catch(Exception e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_txtUserKeyReleased

    private void txtUASearchFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUASearchFKeyReleased
        String a = "";
        if(a.equals(txtUASearchF.getText())){
            txtUser.setText("");
            txtPass.setText("");
            txtAlias.setText("");
            txtType.setText("");
        }else{
            String res = txtUASearchF.getText();
            try{
                String sql = "select * from accounts where "
                        + "username like ? or alias like ? ";
                pst = conn.prepareStatement(sql);
                pst.setString(1, res + "%");
                pst.setString(2, res + "%");
                rs = pst.executeQuery();              
                if(rs.next()){
                    String id = rs.getString("account_id");
                    txtID.setText(id);
                    String user = rs.getString("username");
                    txtUser.setText(user);
                    String pass = rs.getString("password");
                    txtPass.setText(pass);
                    String alias = rs.getString("alias");
                    txtAlias.setText(alias);
                    String type = rs.getString("type");
                    txtType.setText(type);
                }
            }catch(Exception e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_txtUASearchFKeyReleased

    private void txtUASearchTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUASearchTKeyReleased
        String a = "";
        if (a.equals(txtUASearchT.getText())){
            updateUATable();
        }else{
            String res = txtUASearchT.getText();
            try{
                String sql = "select Username, Password, Alias, Type "
                        + "from accounts where username like ? or alias like ? or type like ?";
                pst = conn.prepareStatement(sql);
                pst.setString(1, res + "%");
                pst.setString(2, res + "%");
                pst.setString(3, res + "%");
                rs = pst.executeQuery();
                tblUA.setModel(DbUtils.resultSetToTableModel(rs));
            }catch(Exception e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_txtUASearchTKeyReleased

    private void txtUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserKeyPressed
        evt.getKeyChar();
        if (evt.getKeyCode() >= 65 && evt.getKeyCode() <= 90  || 
                evt.getKeyCode() >= 38 && evt.getKeyCode() <= 47 ||
                evt.getKeyCode() == 8 || evt.getKeyCode() >= 96 && 
                evt.getKeyCode() <=105 || evt.getKeyCode() == 45 || 
                evt.getKeyCode() == 95 || evt.getKeyCode() >= 16 && 
                evt.getKeyCode() <= 20 || evt.getKeyCode() >= 37 &&
                evt.getKeyCode() <= 40 || evt.getKeyCode() == 144 || 
                evt.getKeyCode() == 10 || evt.getKeyCode() == 27){
            
        }else{
            JOptionPane.showMessageDialog(null,"Invalid character entered!",
                    "Invalid character",JOptionPane.WARNING_MESSAGE);
            evt.setKeyCode(8);
        }
    }//GEN-LAST:event_txtUserKeyPressed

    private void txtPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassKeyPressed
        evt.getKeyChar();
        if (evt.getKeyCode() >= 65 && evt.getKeyCode() <= 90  || 
                evt.getKeyCode() >= 48 && evt.getKeyCode() <= 57 ||
                evt.getKeyCode() == 8 || evt.getKeyCode() >= 96 && 
                evt.getKeyCode() <=105 || evt.getKeyCode() == 45 || 
                evt.getKeyCode() == 95 || evt.getKeyCode() >= 16 && 
                evt.getKeyCode() <= 20 || evt.getKeyCode() >= 37 &&
                evt.getKeyCode() <= 40 || evt.getKeyCode() == 144 || 
                evt.getKeyCode() == 10 || evt.getKeyCode() == 27){
            
        }else{
            JOptionPane.showMessageDialog(null,"Invalid character entered!",
                    "Invalid character",JOptionPane.WARNING_MESSAGE);
            evt.setKeyCode(8);
        }
    }//GEN-LAST:event_txtPassKeyPressed

    private void txtConfirmKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConfirmKeyPressed
        evt.getKeyChar();
        if (evt.getKeyCode() >= 65 && evt.getKeyCode() <= 90  || 
                evt.getKeyCode() >= 38 && evt.getKeyCode() <= 47 ||
                evt.getKeyCode() == 8 || evt.getKeyCode() >= 96 && 
                evt.getKeyCode() <=105 || evt.getKeyCode() == 45 || 
                evt.getKeyCode() == 95 || evt.getKeyCode() >= 16 && 
                evt.getKeyCode() <= 20 || evt.getKeyCode() >= 37 &&
                evt.getKeyCode() <= 40 || evt.getKeyCode() == 144 || 
                evt.getKeyCode() == 10 || evt.getKeyCode() == 27){
            
        }else{
            JOptionPane.showMessageDialog(null,"Invalid character entered!",
                    "Invalid character",JOptionPane.WARNING_MESSAGE);
            evt.setKeyCode(8);
        }
    }//GEN-LAST:event_txtConfirmKeyPressed

    private void txtAliasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAliasKeyPressed
        evt.getKeyChar();
        if (evt.getKeyCode() >= 65 && evt.getKeyCode() <= 90  || 
                evt.getKeyCode() == 8 || evt.getKeyCode() == 45 || 
                evt.getKeyCode() == 10 || evt.getKeyCode() >= 16 && 
                evt.getKeyCode() <= 20 || evt.getKeyCode() >= 37 &&
                evt.getKeyCode() <= 40 || evt.getKeyCode() == 144 || 
                evt.getKeyCode() == 27){
            
        }else{
            JOptionPane.showMessageDialog(null,"Invalid character entered!",
                    "Invalid character",JOptionPane.WARNING_MESSAGE);
            evt.setKeyCode(8);
        }
    }//GEN-LAST:event_txtAliasKeyPressed

    private void txtUASearchFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUASearchFKeyPressed
        evt.getKeyChar();
        if (evt.getKeyCode() >= 65 && evt.getKeyCode() <= 90  || 
                evt.getKeyCode() >= 38 && evt.getKeyCode() <= 47 ||
                evt.getKeyCode() == 8 || evt.getKeyCode() >= 96 && 
                evt.getKeyCode() <=105 || evt.getKeyCode() == 45 || 
                evt.getKeyCode() == 95 || evt.getKeyCode() >= 16 && 
                evt.getKeyCode() <= 20 || evt.getKeyCode() >= 37 &&
                evt.getKeyCode() <= 40 || evt.getKeyCode() == 144 || 
                evt.getKeyCode() == 10 || evt.getKeyCode() == 27){
            
        }else{
            JOptionPane.showMessageDialog(null,"Invalid character entered!",
                    "Invalid character",JOptionPane.WARNING_MESSAGE);
            evt.setKeyCode(8);
        }
    }//GEN-LAST:event_txtUASearchFKeyPressed

    private void txtUASearchTKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUASearchTKeyPressed
        evt.getKeyChar();
        if (evt.getKeyCode() >= 65 && evt.getKeyCode() <= 90  || 
                evt.getKeyCode() >= 38 && evt.getKeyCode() <= 47 ||
                evt.getKeyCode() == 8 || evt.getKeyCode() >= 96 && 
                evt.getKeyCode() <=105 || evt.getKeyCode() == 45 || 
                evt.getKeyCode() == 95 || evt.getKeyCode() >= 16 && 
                evt.getKeyCode() <= 20 || evt.getKeyCode() >= 37 &&
                evt.getKeyCode() <= 40 || evt.getKeyCode() == 144 || 
                evt.getKeyCode() == 10 || evt.getKeyCode() == 27){
            
        }else{
            JOptionPane.showMessageDialog(null,"Invalid character entered!",
                    "Invalid character",JOptionPane.WARNING_MESSAGE);
            evt.setKeyCode(8);
        }
    }//GEN-LAST:event_txtUASearchTKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserAccounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserAccounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserAccounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserAccounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UserAccounts frmUA = new UserAccounts();
                frmUA.setLocationRelativeTo(null);
                frmUA.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdAdd;
    private javax.swing.JButton cmdCancel;
    private javax.swing.JButton cmdDel;
    private javax.swing.JButton cmdSave;
    private javax.swing.JButton cmdUpd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblHelper;
    private javax.swing.JLabel lblUser;
    private javax.swing.JTable tblUA;
    private javax.swing.JTextField txtAlias;
    private javax.swing.JPasswordField txtConfirm;
    private javax.swing.JTextField txtID;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtType;
    private javax.swing.JTextField txtUASearchF;
    private javax.swing.JTextField txtUASearchT;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
